name: keyword_env
channels:
- conda-forge
- pkgs/main
- pytorch
dependencies:
- jupyter
- matplotlib
- nltk
- openai
- python=3.11
- pytorch::pytorch
- scikit-learn
- seaborn
- spacy
- torchaudio
- torchvision
- transformers

